spring.application.name=cloud-tasker

spring.datasource.url=jdbc:postgresql://db:5432/cloudtasker
spring.datasource.username=cloudtasker
spring.datasource.password=cloudtasker
spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
